### ISSUE TITLE
The code is missing the "utils.py" file.

### ISSUE THREAD

**Issue by kiritozc** [snowbbbb/EESNN-epileptic-seizure-detection#1]

**Comment by snowbbbb** [comment]
Thank you, we have uploaded the utils.py file

**Comment by kiritozc** [comment]
The project is still missing the two files "data_pku" and "model_input".

**Comment by kiritozc** [comment]
> Thank you, we have uploaded the utils.py file
Thank you for your reply.
The project is still missing the two files "data_pku" and "model_input".

**Comment by kiritozc** [comment]
Done
